# -*- coding: utf-8 -*-
"""Tweets_Scraping_SNScrape.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f0ctTs_B755WxiDQeoUV3XyxWWvUKOK2

## Tweets Scraping with SNScrape

### Install the library
"""

#!pip install snscrape

#!pip3 install googletrans==3.1.0a0

"""### Import the required libraries and make a query"""

import snscrape.modules.twitter as sntwitter
import pandas as pd

query = "online violence to children until:2020-12-01 since:2010-01-01"
tweets = []
limit = 5000


for tweet in sntwitter.TwitterSearchScraper(query).get_items():
    
    # print(vars(tweet))
    # break
    if len(tweets) == limit:
        break
    else:
        tweets.append([tweet.date, tweet.username, tweet.content])
        
df = pd.DataFrame(tweets, columns=['Date', 'User', 'Tweet'])
print(df)

"""### Find the abbreviation for French"""

import googletrans
print(googletrans.LANGUAGES)

"""### Translate English to French using google translate"""

#Translate English to French
from googletrans import *
translator = googletrans.Translator()

df['Tweet'] = df['Tweet'].astype(str) #changing datatype to string
df['translated_tweet'] = df['Tweet'].apply(translator.translate, src='auto', dest='fr').apply(getattr, args=('text',))
df

"""### Save the dataframe to csv format"""

df.to_csv('tweets.csv')